// Generated by gencpp from file object_detect/CenterRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECT_MESSAGE_CENTERREQUEST_H
#define OBJECT_DETECT_MESSAGE_CENTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detect
{
template <class ContainerAllocator>
struct CenterRequest_
{
  typedef CenterRequest_<ContainerAllocator> Type;

  CenterRequest_()
    : center_x(0)
    , center_y(0)  {
    }
  CenterRequest_(const ContainerAllocator& _alloc)
    : center_x(0)
    , center_y(0)  {
  (void)_alloc;
    }



   typedef int64_t _center_x_type;
  _center_x_type center_x;

   typedef int64_t _center_y_type;
  _center_y_type center_y;





  typedef boost::shared_ptr< ::object_detect::CenterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detect::CenterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CenterRequest_

typedef ::object_detect::CenterRequest_<std::allocator<void> > CenterRequest;

typedef boost::shared_ptr< ::object_detect::CenterRequest > CenterRequestPtr;
typedef boost::shared_ptr< ::object_detect::CenterRequest const> CenterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detect::CenterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detect::CenterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'object_detect': ['/home/castle/cbot/src/object_detect/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::CenterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::CenterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::CenterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::CenterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::CenterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::CenterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detect::CenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d5102ab93497020cd2f933773fdfb27";
  }

  static const char* value(const ::object_detect::CenterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d5102ab93497020ULL;
  static const uint64_t static_value2 = 0xcd2f933773fdfb27ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detect::CenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detect/CenterRequest";
  }

  static const char* value(const ::object_detect::CenterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detect::CenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 center_x\n\
int64 center_y\n\
";
  }

  static const char* value(const ::object_detect::CenterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detect::CenterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center_x);
      stream.next(m.center_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CenterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detect::CenterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detect::CenterRequest_<ContainerAllocator>& v)
  {
    s << indent << "center_x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.center_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECT_MESSAGE_CENTERREQUEST_H
