// Generated by gencpp from file object_detect/object_resultResponse.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECT_MESSAGE_OBJECT_RESULTRESPONSE_H
#define OBJECT_DETECT_MESSAGE_OBJECT_RESULTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detect
{
template <class ContainerAllocator>
struct object_resultResponse_
{
  typedef object_resultResponse_<ContainerAllocator> Type;

  object_resultResponse_()
    : x1(0)
    , y1(0)
    , ss(0)  {
    }
  object_resultResponse_(const ContainerAllocator& _alloc)
    : x1(0)
    , y1(0)
    , ss(0)  {
  (void)_alloc;
    }



   typedef int64_t _x1_type;
  _x1_type x1;

   typedef int64_t _y1_type;
  _y1_type y1;

   typedef int64_t _ss_type;
  _ss_type ss;





  typedef boost::shared_ptr< ::object_detect::object_resultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detect::object_resultResponse_<ContainerAllocator> const> ConstPtr;

}; // struct object_resultResponse_

typedef ::object_detect::object_resultResponse_<std::allocator<void> > object_resultResponse;

typedef boost::shared_ptr< ::object_detect::object_resultResponse > object_resultResponsePtr;
typedef boost::shared_ptr< ::object_detect::object_resultResponse const> object_resultResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detect::object_resultResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detect::object_resultResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'object_detect': ['/home/castle/cbot/src/object_detect/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::object_resultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::object_resultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::object_resultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::object_resultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::object_resultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::object_resultResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detect::object_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "865d1464aed1299ac0a16f8c224ff420";
  }

  static const char* value(const ::object_detect::object_resultResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x865d1464aed1299aULL;
  static const uint64_t static_value2 = 0xc0a16f8c224ff420ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detect::object_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detect/object_resultResponse";
  }

  static const char* value(const ::object_detect::object_resultResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detect::object_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x1\n\
int64 y1\n\
int64 ss\n\
\n\
\n\
";
  }

  static const char* value(const ::object_detect::object_resultResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detect::object_resultResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.ss);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct object_resultResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detect::object_resultResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detect::object_resultResponse_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y1);
    s << indent << "ss: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ss);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECT_MESSAGE_OBJECT_RESULTRESPONSE_H
